language: python
python:
  - "2.7"
before_script:
  - apt-get install libgdal1-dev
install:
  - pip install -r requirements.txt --use-mirrors
script: nosetests
notifications:
  email: false
  irc: "irc.freenode.net#okfn-dev"
